package ICO_EDA_1359.Pilas;

import ICO_EDA_1359.Nodo;

public class MainPila {
    public static void main(String[] args) {
        System.out.println("________________________PILA BACIA DESDE EL INICIO__________________________________");
        Pila pila1 = new Pila();
        pila1.Peek();
        System.out.println("_______________________________Método Push__________________________________________");
        pila1.Push("Pepe");
        pila1.Peek();
        System.out.println(pila1);
        pila1.Push(30);
        pila1.Peek();
        System.out.println(pila1);
        pila1.Push("Naranjo");
        pila1.Peek();
        System.out.println(pila1);
        pila1.Push(1234);
        pila1.Peek();
        System.out.println(pila1);
        pila1.Push("Zapato");
        pila1.Peek();
        System.out.println(pila1);
        System.out.println("_______________________________Método Pop__________________________________________");
        pila1.Pop();
        pila1.Peek();
        System.out.println(pila1);
        pila1.Pop();
        pila1.Peek();
        System.out.println(pila1);
        pila1.Pop();
        pila1.Peek();
        System.out.println(pila1);
        pila1.Pop();
        pila1.Peek();
        System.out.println(pila1);
        pila1.Pop();
        pila1.Peek();
        pila1.Pop();
        System.out.println("________________________PILA CON VALORES INICIALES__________________________________");
        Pila pila2 = new Pila(new Nodo("Andres", new Nodo(false)));
        pila2.Peek();
        System.out.println("_______________________________Método Push__________________________________________");
        pila2.Push("Pepe");
        pila2.Peek();
        System.out.println(pila2);
        pila2.Push(30);
        pila2.Peek();
        System.out.println(pila2);
        pila2.Push("Naranjo");
        pila2.Peek();
        System.out.println(pila2);
        pila2.Push(1234);
        pila2.Peek();
        System.out.println(pila2);
        pila2.Push("Zapato");
        pila2.Peek();
        System.out.println(pila2);
        System.out.println("_______________________________Método Pop__________________________________________");
        pila2.Pop();
        pila2.Peek();
        System.out.println(pila2);
        pila2.Pop();
        pila2.Peek();
        System.out.println(pila2);
        pila2.Pop();
        pila2.Peek();
        System.out.println(pila2);
        pila2.Pop();
        pila2.Peek();
        System.out.println(pila2);
        pila2.Pop();
        pila2.Peek();
        System.out.println(pila2);
        pila2.Pop();
        pila2.Peek();
    }
}
